---
title: "Appendix:           Shoe-sales Time Series Analysis"
author: "Fengyang Lin & Rui Ju"
date: "4/16/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```
```{r}
library(tidyverse)
library(tsoutliers)
library(astsa)
library(tseries)
library(forecast)
library(stats)
```

```{r, fig.height=3}
sales <- read.table("MRTSSM4482USN.csv",header=TRUE,sep=",")
ts_sales <- ts(sales$MRTSSM4482USN[150:303])
log_sales <- log(ts_sales)
plot(ts_sales,type = "l", ylab = "sales", main = "sales")
plot(log_sales, type = "l", main = "log_sales")
```

```{r}
outliers_sales <- tso(log_sales)
outliers_sales
```

```{r}
par(mfrow=c(2,1))
ts.plot(diff(log_sales), main = "First Difference")
ts.plot(diff(diff(log_sales), 12), main = "First Difference & Seasonal Difference")
```

```{r}
acf(diff(diff(log_sales), 12),150)
pacf(diff(diff(log_sales), 12),  150)
```

```{r}
adf.test(diff(diff(log_sales), 12), k = 12)
```

```{r}
model1 <- arima(log_sales, c(5,1,5), seasonal = list(order = c(0,1,1), period = 12))
summary(model1)
res1 <- residuals(model1)
acf(res1,100)
pacf(res1,100)
ts.plot(res1)
Box.test(res1, type = "Ljung")
pred1 <-exp(forecast(model1, 10)$mean)
accuracy(pred1, sales$MRTSSM4482USN[304:313])
```


```{r}
model2 <- arima(log_sales, c(6,1,4), seasonal = list(order = c(0,1,1), period = 12))
summary(model2)
res2 <- residuals(model2)
ts.plot(res2)
par(mfrow=c(1,2))
acf(res2,200)
pacf(res2,200)
Box.test(res2, type = "Ljung")
pred2 <-exp(forecast(model2, 10)$mean)
accuracy(pred2, sales$MRTSSM4482USN[304:313])
```

```{r}
model3 <- arima(log_sales, c(5,1,4), seasonal = list(order = c(0,1,1), period = 12))
summary(model3)
res3 <- residuals(model3)
acf(res3,100)
pacf(res3,100)
ts.plot(res3)
Box.test(res3, type = "Ljung")
pred3 <-exp(forecast(model3, 10)$mean)
accuracy(pred3, sales$MRTSSM4482USN[304:313])
```
```{r}
model4 <- arima(log_sales, c(5,1,3), seasonal = list(order = c(0,1,1), period = 12))
summary(model4)
res4 <- residuals(model4)
acf(res4,100)
pacf(res4,100)
ts.plot(res4)
Box.test(res4, type = "Ljung")
pred4 <-exp(forecast(model4, 10)$mean)
accuracy(pred4, sales$MRTSSM4482USN[304:313])
```

```{r}
model5 <- arima(log_sales, c(3,1,5), seasonal = list(order = c(0,1,1), period = 12))
#summary(model5)
res5 <- residuals(model5)
acf(res5,100)
pacf(res5,100)
ts.plot(res5)
#Box.test(res5, type = "Ljung")
pred5 <-exp(forecast(model5, 10)$mean)
accuracy(pred5, sales$MRTSSM4482USN[304:313])
```
```{r}
model6 <- arima(log_sales, c(4,1,4), seasonal = list(order = c(0,1,1), period = 12))
summary(model6)
res6 <- residuals(model6)
acf(res6,100)
pacf(res6,100)
ts.plot(res6)
Box.test(res6, type = "Ljung")
pred6 <-exp(forecast(model6, 10)$mean)
accuracy(pred6, sales$MRTSSM4482USN[304:313])
```

```{r}
pred5
```

```{r}
plot(sales$MRTSSM4482USN[150:303], type="l",ylab = "sales",xlab = "Time", main = "ARIMA(6,1,4)(1,1,1)12")
legend(1,4400,legend=c("actural data","fitted data"), fill=FALSE,col = c("black","red"), lty=c(1,2),lwd=c(1,1),merge = TRUE)
lines(1:154, exp(fitted(model5)), lty=2, col="red")
```

```{r}
plot(sales$MRTSSM4482USN[150:313], type="l", xlim=c(0, 175),ylab = "sales", xlab = "t", main = "ARIMA Analysis\n Predicted & Actural Value")
legend(1,4400,legend=c("actural data","predicted training data","predicted test data","predicted test data boundary"), fill=FALSE,col = c("black","red","blue","purple"), lty=c(1,2,6,3),lwd=c(1,1,2.5,1),merge = TRUE)
lines(exp(fitted(model5)), lty=2, col="red")
lines(exp(pred5), col = "blue", lty = 6, lwd = 2.5)
matlines(155:164, exp(as.data.frame(forecast(model5, 10))[,4:5]), col = "purple", lty=3)
```

```{r}
par(mfrow=c(2,1)) 
spec.pgram(ts_sales)
spec.pgram(log_sales)
```

```{r}
par(mfrow=c(2,1))
spec.pgram(log_sales,kernel("daniell",1),taper=0,main="Series:log_sales \nSmoothed Periodogram: daniell m=1")
spec.pgram(log_sales,kernel("daniell",3),taper=0,main="Series:log_sales \nSmoothed Periodogram: daniell m=3")
```

```{r}
par(mfrow=c(2,1))
spec.pgram(log_sales,kernel("modified.daniell",1),taper=0,main="Series:log_sales \nSmoothed Periodogram: modified daniell m=1")
spec.pgram(log_sales,kernel("modified.daniell",c(1,1)),taper=0,main="Series:log_sales \nSmoothed Periodogram: apply twice: modified daniell m=1")
```
```{r}
pgram <- spec.pgram(log_sales,kernel("modified.daniell",c(1,1,1)),taper=0.2,main="Smoothed Periodogram\n apply 3 times: modified daniell m=1 taper=0.2")
key_freq_ind <-  c(1, which(diff(sign(diff(pgram$spec)))==-2) + 1,length(pgram$spec)) 
key_freq <- pgram$freq[key_freq_ind]
abline(v=key_freq, lty=2)
```
```{r}
round(key_freq[order(pgram$spec[key_freq_ind], decreasing = TRUE)],2)
round(1/key_freq[order(pgram$spec[key_freq_ind], decreasing = TRUE)])
```

```{r}
t <- 1:length(log_sales)
top_freq <- key_freq[order(pgram$spec[key_freq_ind], decreasing = T)][1:3]
periodic_terms <- do.call(cbind, lapply(top_freq, function(freq) {
  cbind(cos(2 * pi * freq * t), sin(2 * pi * freq * t))
}))
df <- data.frame(log_sales, t, periodic_terms)
fit_final <- lm(log_sales ~ ., df)
plot(t, log_sales, type="l")
lines(t, fit_final$fitted.values, lty=2, col="red")
```
```{r}
t_new <- (tail(t, 1) + 1):(tail(t, 1) + 10)
periodic_terms_new <- do.call(cbind, lapply(top_freq, function(freq) {
  cbind(cos(2 * pi * freq * t_new), sin(2 * pi * freq * t_new))
}))
df_new <- data.frame(t_new, periodic_terms_new)
colnames(df_new) <- colnames(df)[-1]
predictions <- predict.lm(fit_final, newdata=df_new,interval="prediction")
plot(t, exp(log_sales), type="l", xlim=c(0, tail(t_new, 1)),ylab = "sales (remove log)", main = "Spectral Analysis\n Predicted & Actural Value")
legend(1,4400,legend=c("actural data","predicted training data","predicted test data","predicted test data boundary"), fill=FALSE,col = c("black","red","blue","purple"), lty=c(1,2,6,3),lwd=c(1,1,2.5,1),merge = TRUE)
lines(t, exp(fit_final$fitted.values), lty=2, col="red")
lines(t_new, exp(predictions[, "fit"]), col="blue",lty=6,lwd=2.5)
matlines(t_new, exp(predictions[, 2:3]), col = "purple", lty=3)


```
```{r}
accuracy(exp(predictions[, "fit"]),exp(log(sales$MRTSSM4482USN[304:313])))
```
```{r, fig.height=10}
par(mfrow = c(2,1))
plot(sales$MRTSSM4482USN[150:313], type="l", xlim=c(0, 175),ylab = "sales", xlab = "t", main = "Predicted & Actural Value for two models \n ARIMA")
lines(exp(fitted(model5)), lty=2, col="red")
lines(pred5, col = "red", lty = 6, lwd = 2.5)
plot(c(t,t_new), sales$MRTSSM4482USN[150:313], type="l",ylab = "sales",xlab = "t",main = "Spectral Analysis")
legend(1,4400,legend=c("actural data","arima","spectral"), fill=FALSE,col = c("black","red","blue"), lty=c(1,2,2),lwd=c(1,1,1),merge = TRUE)
lines(t, exp(fit_final$fitted.values), lty=2, col=20)
lines(t_new, exp(predictions[, "fit"]), col="blue",lty=6,lwd=2.5)

```
```{r}
pred <- exp(forecast(model5, 22)$mean)
pred[11:22]
```


```{r}
plot(sales$MRTSSM4482USN[150:313], type="l", xlim=c(0, 175), ylab = "sales", xlab = "t", main = "Forecast")
legend(1,4400,legend=c("actual data","forecast"), fill=FALSE,col = c("black","red"),
lty=c(1,2,6,3),lwd=c(1,2.5), merge = TRUE)
lines(164:176,pred[10:22], col = "red", lty = 6, lwd = 2.5)
```


